// Auto-generated by scripts/generate-build-info.mjs — DO NOT EDIT.
// Wird bei jedem 'npm run dev' und 'npm run build' regeneriert.
export const BUILD_INFO = {
  "version": "0.669",
  "sha": "de5b0b4",
  "branch": "redesign",
  "buildAt": "2026-05-04T23:00:13.947Z",
  "files": 251,
  "lines": 35698,
  "words": 141876
} as const;
