// Auto-generated by scripts/generate-build-info.mjs — DO NOT EDIT.
// Wird bei jedem 'npm run dev' und 'npm run build' regeneriert.
export const BUILD_INFO = {
  "version": "0.1108",
  "sha": "ec95bb1",
  "branch": "audit-umsetzung",
  "buildAt": "2026-09-01T08:28:17.055Z",
  "files": 520,
  "lines": 80642,
  "words": 333175
} as const;
